name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.4.0'  # 使用指定的Dart SDK版本

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            make windows-prepare
          elif [ "$RUNNER_OS" == "Linux" ]; then
            make linux-prepare
          elif [ "$RUNNER_OS" == "macOS" ]; then
            make macos-prepare
          fi

      - name: Run tests
        run: flutter test

      - name: Build application
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            flutter build apk
          elif [ "$RUNNER_OS" == "macOS" ]; then
            flutter build ios
            flutter build macos
          elif [ "$RUNNER_OS" == "Windows" ]; then
            flutter build windows
          fi

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: flutter-artifacts
          path: |
            build/app/outputs/apk/  # Android APK
            build/ios/iphoneos/*.ipa  # iOS IPA
            build/macos/Build/Products/Release/  # macOS App
            build/windows/runner/Release/*.exe  # Windows Executable



