name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Prepare dependencies
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            make windows-prepare
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            make macos-prepare
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            make android-prepare
          fi

      - name: Run project
        run: |
          echo "Running Flutter project..."
          flutter run || echo "Running project failed"

      - name: Build project
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            flutter build windows
            echo "Build for Windows completed."
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            flutter build macos
            echo "Build for macOS completed."
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            flutter build apk
            echo "Build for Android completed."
          fi

      - name: Upload Release Artifacts
        if: success() && (matrix.os == 'windows-latest' || matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest')
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/windows/runner/Release/*
            build/macos/Build/Products/Release/*
            build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release
        if: success() && (matrix.os == 'windows-latest' || matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets to Release
        if: steps.create_release.outputs.id
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          assets: |
            build/windows/runner/Release/*
            build/macos/Build/Products/Release/*
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
