name: Flutter CI

on:
  push:
    branches:
      - main  # 或你要监控的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 选择适合的操作系统

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v3  # 使用最新的 v3 版本
        with:
          flutter-version: '3.4.0'  # 确保使用正确的版本
          channel: 'stable'  # 指定稳定的渠道

      - name: Install dependencies
        run: flutter pub get

      - name: Prepare dependencies for Windows
        if: runner.os == 'Windows'
        run: make windows-prepare

      - name: Prepare dependencies for Android
        if: runner.os == 'Linux'
        run: make android-prepare

      - name: Run Flutter project
        run: flutter run --no-sound-null-safety  # 根据需要添加参数

      - name: Build APK
        run: flutter build apk --release

      - name: Build Windows application
        if: runner.os == 'Windows'
        run: flutter build windows --release

      - name: Upload APK Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk  # 根据实际路径调整

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/runner/Release/YourApp.exe  # 根据实际路径调整

