name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # 确保使用包含 Dart 3.9.0 的版本

      - name: Check Flutter and Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Prepare Dependencies for Windows
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "Preparing dependencies for Windows..."
            make windows-prepare || { echo "Failed to prepare Windows dependencies"; exit 1; }
          fi

      - name: Prepare Dependencies for Android
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            echo "Preparing dependencies for Android..."
            make android-prepare || { echo "Failed to prepare Android dependencies"; exit 1; }
          fi

      - name: Run Flutter
        run: flutter run

      - name: Build APK
        run: flutter build apk

      - name: Build Windows
        run: flutter build windows

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/runner/Release/*.exe


