name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'  # 确保该版本支持 Dart SDK 3.4.0

      - name: Prepare dependencies
        run: |
          flutter --disable-telemetry
          set -x  # 启用调试输出
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            make windows-prepare
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            make android-prepare
          fi

      - name: Run Flutter
        run: flutter run

      - name: Build APK
        run: flutter build apk

      - name: Build Windows
        run: flutter build windows

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/runner/Release/YourApp.exe  # 请替换为实际可执行文件名


